### ISSUE TITLE
$staticResource after {{#each}}  notworking

### ISSUE THREAD

**Issue by inggil2407** [jsreport/jsreport-static-resources#2]
i need {{$staticResource}} after {{#each blah}}, can i do that?

**Comment by pofider** [comment]
Of course, you just need to get to outer scope `{{../$staticResource}}` or to root `{{@root.$staticResource}}`

http://stackoverflow.com/questions/12297959/access-properties-of-the-parent-with-a-handlebars-each-loop
http://stackoverflow.com/questions/17364897/access-to-root-context-in-handlebar-js-template
