### ISSUE TITLE
static resources with JADE

### ISSUE THREAD

**Issue by danykina** [jsreport/jsreport-static-resources#4]
I use jsreport-jade to write html and #{{staticResources}} not work with this.

How can i do? Thanks

**Comment by pofider** [comment]
Not very familiar with jade, but should it be just in single bracket format `#{staticResources}` ?

If you use html recipe and inspect the output, what does it print?

**Comment by danykina** [comment]
With #{staticResources} doesn't use the library jsreport-staticResources, because the var "staticResources" undefined and in the url is it.
http://localhost:40017/api/**undefined**/estimate-print/css/style.css this is the url where search the files.
Why undefined?

While with {{$staticResources}}
http://localhost:40017/api/%7B%7B$staticResources%7D%7D/estimate-print/css/style.css

**Comment by danykina** [comment]
Ideas?

**Comment by pofider** [comment]
I'm lost in translation here :). 

If you didn't install the `jsreport-static-resources` the value of `#{staticResources}` gonna be `undefined` for sure.

**Comment by danykina** [comment]
I have already installed jsreport-static-resources

**Comment by pofider** [comment]
Can you share the whole line you put in your template which includes `#{staticResources}`? 

I've just tried it with jade
- `npm install jsreport-jade`
- `npm install jsreport-static-resources`
- add to template line `<script src="#{$staticResources}/test.js"></script>`
- and this nicely resolves to `<script src="http://localhost:5488/static-resources/test.js"></script>`
- and `test.js` is than accessible from directory `/data/staticResources/test.js` as default

**Comment by danykina** [comment]
Work in content.jade but not in header.jade and footer.jade
I use phantom-pdf
The directory is resolved  in "http://localhost:5488/static-resources/" but when i include the css in header.jade or footer.jade returns a error.

```
`Error occured - Error during rendering report: Command failed: C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-phantom-pdf\node_modules\phantom-html-to-pdf\node_modules\phantomjs\lib\phantom\phantomjs.exe --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-phantom-pdf\node_modules\phantom-html-to-pdf\lib\scripts\standaloneScript.js C:\Users\test\AppData\Local\Temp\jsreport-temp\fc3a6af0-7f10-11e6-a96d-ebebe6baf5f8settings.html

Stak - Error: Command failed: C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-phantom-pdf\node_modules\phantom-html-to-pdf\node_modules\phantomjs\lib\phantom\phantomjs.exe --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-phantom-pdf\node_modules\phantom-html-to-pdf\lib\scripts\standaloneScript.js C:\Users\test\AppData\Local\Temp\jsreport-temp\fc3a6af0-7f10-11e6-a96d-ebebe6baf5f8settings.html
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-core\lib\render\render.js:143:54
    at _fulfilled (C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-core\node_modules\listener-collection\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-core\node_modules\listener-collection\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-core\node_modules\listener-collection\node_modules\q\q.js:756:13)
    at C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-core\node_modules\listener-collection\node_modules\q\q.js:564:44
    at flush (C:\Users\test\Documents\test\test\test\node_modules\jsreport\node_modules\jsreport-core\node_modules\listener-collection\node_modules\q\q.js:110:17)`
```

**Comment by pofider** [comment]
What exactly you put in header/footer and content? I cannot replicate such error.

**Comment by danykina** [comment]
There are the contents in JADE and it works, but when i insert this string in the code JADE `link(rel='stylesheet', href="#{$staticResources}/fileProject/css/style.css")`
returns the error

**Comment by danykina** [comment]
If i try to print the string
 `link(rel='stylesheet', href="#{$staticResources}/fileProject/css/style.css")` with tag "p",
 the directory is correct `http://localhost:5488/static-resources/fileProject/css/style.css`
but not work anyway

**Comment by danykina** [comment]
I tryed to create a server http with WampServer in my pc and if i link this string `http://localhost/fileProject/css/style.css` it works without errors!
But I won't create a second server http, i want use a jsreport server

**Comment by pofider** [comment]
I was able to replicate the phantomjs fail. Unfortunately phantomjs seems to fail if you reference the external css in the header. 

You may need to inline the css using a child template or using a custom script.

**Comment by danykina** [comment]
Can you try to create a jsreport server?

```
npm install jsreport
npm install jsreport-jade
npm install jsreport-static-resources

Insert this file content.jade such as content
Insert this file footer.jade such as footer
Insert this file css/style.css into staticResources folder
```

and see if returns the errors

[jade_jsreport_test.zip](https://github.com/jsreport/jsreport-static-resources/files/482366/jade_jsreport_test.zip)

**Comment by danykina** [comment]
Temporarily i resolved with css inline, but i have a other problem, the rendering of css font not work
[other issue](https://github.com/jsreport/jsreport-phantom-pdf/issues/6)

**Comment by pofider** [comment]
Summary:
Not a jade or static-resources issue. 
Real problem: phantomjs doesn't support external links in the header
jsreport solution: use child templates or custom script to inline the style in header
